// Code generated by cmd/introspect; DO NOT EDIT.

package dispatch

import (
	"context"
	"fmt"

	"github.com/slack-go/slack"
)

func dispatchAuthTest(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for auth.test")
}

func dispatchAddBookmark(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for bookmarks.add")
}

func dispatchEditBookmark(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for bookmarks.edit")
}

func dispatchListBookmarks(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for bookmarks.list")
}

func dispatchRemoveBookmark(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for bookmarks.remove")
}

func dispatchGetBotInfo(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for bots.info")
}

func dispatchDeleteMessage(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for chat.delete")
}

func dispatchGetPermalink(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for chat.getPermalink")
}

func dispatchPostEphemeral(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for chat.postEphemeral")
}

func dispatchPostMessage(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for chat.postMessage")
}

func dispatchScheduleMessage(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for chat.scheduleMessage")
}

func dispatchUpdateMessage(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for chat.update")
}

func dispatchArchiveConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.archive")
}

func dispatchCloseConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.close")
}

func dispatchCreateConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.create")
}

func dispatchGetConversationHistory(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.history")
}

func dispatchGetConversationInfo(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.info")
}

func dispatchInviteUsersToConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.invite")
}

func dispatchJoinConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.join")
}

func dispatchKickUserFromConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.kick")
}

func dispatchLeaveConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.leave")
}

func dispatchGetConversations(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.list")
}

func dispatchMarkConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.mark")
}

func dispatchGetUsersInConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.members")
}

func dispatchOpenConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.open")
}

func dispatchRenameConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.rename")
}

func dispatchGetConversationReplies(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.replies")
}

func dispatchSetPurposeOfConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.setPurpose")
}

func dispatchSetTopicOfConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.setTopic")
}

func dispatchUnArchiveConversation(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for conversations.unarchive")
}

func dispatchOpenDialog(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for dialog.open")
}

func dispatchEndDND(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for dnd.endDnd")
}

func dispatchEndSnooze(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for dnd.endSnooze")
}

func dispatchGetDNDInfo(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for dnd.info")
}

func dispatchSetSnooze(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for dnd.setSnooze")
}

func dispatchGetDNDTeamInfo(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for dnd.teamInfo")
}

func dispatchGetEmoji(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for emoji.list")
}

func dispatchDeleteFile(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for files.delete")
}

func dispatchGetFileInfo(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for files.info")
}

func dispatchGetFiles(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for files.list")
}

func dispatchRevokeFilePublicURL(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for files.revokePublicURL")
}

func dispatchShareFilePublicURL(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for files.sharedPublicURL")
}

func dispatchAddPin(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for pins.add")
}

func dispatchListPins(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for pins.list")
}

func dispatchRemovePin(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for pins.remove")
}

func dispatchAddReaction(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for reactions.add")
}

func dispatchGetReactions(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for reactions.get")
}

func dispatchListReactions(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for reactions.list")
}

func dispatchRemoveReaction(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for reactions.remove")
}

func dispatchDeleteReminder(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for reminders.delete")
}

func dispatchListReminders(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for reminders.list")
}

func dispatchSearchFiles(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for search.files")
}

func dispatchSearchMessages(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for search.messages")
}

func dispatchAddStar(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for stars.add")
}

func dispatchListStars(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for stars.list")
}

func dispatchRemoveStar(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for stars.remove")
}

func dispatchGetTeamInfo(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for team.info")
}

func dispatchCreateUserGroup(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for usergroups.create")
}

func dispatchDisableUserGroup(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for usergroups.disable")
}

func dispatchEnableUserGroup(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for usergroups.enable")
}

func dispatchGetUserGroups(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for usergroups.list")
}

func dispatchUpdateUserGroup(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for usergroups.update")
}

func dispatchGetUserGroupMembers(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for usergroups.users.list")
}

func dispatchUpdateUserGroupMembers(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for usergroups.users.update")
}

func dispatchGetUserPresence(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for users.getPresence")
}

func dispatchGetUserInfo(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for users.info")
}

func dispatchGetUsers(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for users.list")
}

func dispatchGetUserProfile(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for users.profile.get")
}

func dispatchSetUserPresence(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for users.setPresence")
}

func dispatchOpenView(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for views.open")
}

func dispatchPublishView(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for views.publish")
}

func dispatchPushView(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for views.push")
}

func dispatchUpdateView(_ context.Context, _ *slack.Client, _ map[string]any) (any, error) {
	return nil, fmt.Errorf("not yet implemented for views.update")
}

func init() {
	RegisterDispatch("auth.test", dispatchAuthTest)
	RegisterDispatch("bookmarks.add", dispatchAddBookmark)
	RegisterDispatch("bookmarks.edit", dispatchEditBookmark)
	RegisterDispatch("bookmarks.list", dispatchListBookmarks)
	RegisterDispatch("bookmarks.remove", dispatchRemoveBookmark)
	RegisterDispatch("bots.info", dispatchGetBotInfo)
	RegisterDispatch("chat.delete", dispatchDeleteMessage)
	RegisterDispatch("chat.getPermalink", dispatchGetPermalink)
	RegisterDispatch("chat.postEphemeral", dispatchPostEphemeral)
	RegisterDispatch("chat.postMessage", dispatchPostMessage)
	RegisterDispatch("chat.scheduleMessage", dispatchScheduleMessage)
	RegisterDispatch("chat.update", dispatchUpdateMessage)
	RegisterDispatch("conversations.archive", dispatchArchiveConversation)
	RegisterDispatch("conversations.close", dispatchCloseConversation)
	RegisterDispatch("conversations.create", dispatchCreateConversation)
	RegisterDispatch("conversations.history", dispatchGetConversationHistory)
	RegisterDispatch("conversations.info", dispatchGetConversationInfo)
	RegisterDispatch("conversations.invite", dispatchInviteUsersToConversation)
	RegisterDispatch("conversations.join", dispatchJoinConversation)
	RegisterDispatch("conversations.kick", dispatchKickUserFromConversation)
	RegisterDispatch("conversations.leave", dispatchLeaveConversation)
	RegisterDispatch("conversations.list", dispatchGetConversations)
	RegisterDispatch("conversations.mark", dispatchMarkConversation)
	RegisterDispatch("conversations.members", dispatchGetUsersInConversation)
	RegisterDispatch("conversations.open", dispatchOpenConversation)
	RegisterDispatch("conversations.rename", dispatchRenameConversation)
	RegisterDispatch("conversations.replies", dispatchGetConversationReplies)
	RegisterDispatch("conversations.setPurpose", dispatchSetPurposeOfConversation)
	RegisterDispatch("conversations.setTopic", dispatchSetTopicOfConversation)
	RegisterDispatch("conversations.unarchive", dispatchUnArchiveConversation)
	RegisterDispatch("dialog.open", dispatchOpenDialog)
	RegisterDispatch("dnd.endDnd", dispatchEndDND)
	RegisterDispatch("dnd.endSnooze", dispatchEndSnooze)
	RegisterDispatch("dnd.info", dispatchGetDNDInfo)
	RegisterDispatch("dnd.setSnooze", dispatchSetSnooze)
	RegisterDispatch("dnd.teamInfo", dispatchGetDNDTeamInfo)
	RegisterDispatch("emoji.list", dispatchGetEmoji)
	RegisterDispatch("files.delete", dispatchDeleteFile)
	RegisterDispatch("files.info", dispatchGetFileInfo)
	RegisterDispatch("files.list", dispatchGetFiles)
	RegisterDispatch("files.revokePublicURL", dispatchRevokeFilePublicURL)
	RegisterDispatch("files.sharedPublicURL", dispatchShareFilePublicURL)
	RegisterDispatch("pins.add", dispatchAddPin)
	RegisterDispatch("pins.list", dispatchListPins)
	RegisterDispatch("pins.remove", dispatchRemovePin)
	RegisterDispatch("reactions.add", dispatchAddReaction)
	RegisterDispatch("reactions.get", dispatchGetReactions)
	RegisterDispatch("reactions.list", dispatchListReactions)
	RegisterDispatch("reactions.remove", dispatchRemoveReaction)
	RegisterDispatch("reminders.delete", dispatchDeleteReminder)
	RegisterDispatch("reminders.list", dispatchListReminders)
	RegisterDispatch("search.files", dispatchSearchFiles)
	RegisterDispatch("search.messages", dispatchSearchMessages)
	RegisterDispatch("stars.add", dispatchAddStar)
	RegisterDispatch("stars.list", dispatchListStars)
	RegisterDispatch("stars.remove", dispatchRemoveStar)
	RegisterDispatch("team.info", dispatchGetTeamInfo)
	RegisterDispatch("usergroups.create", dispatchCreateUserGroup)
	RegisterDispatch("usergroups.disable", dispatchDisableUserGroup)
	RegisterDispatch("usergroups.enable", dispatchEnableUserGroup)
	RegisterDispatch("usergroups.list", dispatchGetUserGroups)
	RegisterDispatch("usergroups.update", dispatchUpdateUserGroup)
	RegisterDispatch("usergroups.users.list", dispatchGetUserGroupMembers)
	RegisterDispatch("usergroups.users.update", dispatchUpdateUserGroupMembers)
	RegisterDispatch("users.getPresence", dispatchGetUserPresence)
	RegisterDispatch("users.info", dispatchGetUserInfo)
	RegisterDispatch("users.list", dispatchGetUsers)
	RegisterDispatch("users.profile.get", dispatchGetUserProfile)
	RegisterDispatch("users.setPresence", dispatchSetUserPresence)
	RegisterDispatch("views.open", dispatchOpenView)
	RegisterDispatch("views.publish", dispatchPublishView)
	RegisterDispatch("views.push", dispatchPushView)
	RegisterDispatch("views.update", dispatchUpdateView)
}
